create table curso (
    id bigint generated by default as identity,
    nome varchar(255) not null,
    unidade_sigla varchar(80),
    primary key (id)
);

create index ix_curso_nome
    on curso (nome);

alter table pessoa
    add column curso_id bigint;

create index ix_pessoa_curso
    on pessoa (curso_id);

alter table pessoa
    add constraint fk_pessoa_curso
    foreign key (curso_id)
    references curso;
