spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/procel_analytics
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

procel:
  rooms:
    source: cobalto # cobalto | resource
    resource-path: seed/cobalto-compartimentos.sample.json

  cobalto:
    rooms:
      url: https://cobalto.ufpel.edu.br/servicosgerais/consultas/salasDeAula/listaSalas/
      timeout-ms: 10000
      php-sessid: ""   # opcional (se precisar)